# Site settings
title: Mark Hazleton
email: "" # Removed email
description: > # this means to ignore newlines until "baseurl:"
  Mark Hazleton on GitHub
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://markhazleton.com" # Updated to MarkHazleton.com
author:
  name: Mark Hazleton
  email: "" # Removed email

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap # Add a sitemap generator for better SEO
  - jekyll-seo-tag # Enhance metadata for SEO

# Remote theme
remote_theme: null

# Minima theme settings
minima:
  skin: dark
  social_links:
    twitter: markhazleton
    github: markhazleton
    linkedin: markhazleton
    stackoverflow: "479571"

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - /docs/
  - /README.md
  - node_modules/
  - vendor/

# Additional configurations
sass:
  style: compressed # Compress CSS for better performance
