# Site settings
title: Mark Hazleton
email: mark.hazleton@controlorigins.com
description: >- # this means to ignore newlines until "baseurl:"
  Mark Hazleton on GitHub
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://markhazleton.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Mark Hazleton
  email: mark.hazleton@controlorigins.com
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jemoji
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    twitter: markhazleton
    github: markhazleton
    linkedin: markhazleton
    stackoverflow: "479571"
exclude:
  - Gemfile
  - Gemfile.lock
